dynamic service page
Alv-no/alv-website pull request #261
Opened 2021-03-08 14:14 UTC by mikkelcodes

2021-03-08 15:40 UTC, TheKnarf commented on packages/website/src/pages/vi-tilbyr/index.js
> +                console.log(card);
...

2021-03-08 15:41 UTC, TheKnarf approved these changes

2021-03-08 18:34 UTC, TheKnarf approved these changes

2021-03-08 18:35 UTC, TheKnarf requested changes
Can we stop adding video files to git? That inflates the repo size quite a lot. We allready have a solution for adding them to Sanity.

2021-03-09 01:59 UTC, mikkelcodes commented
> Can we stop adding video files to git? That inflates the repo size quite a lot. We allready have a solution for adding them to Sanity.

Ow... xD I'll amend it out. It is even redundant as the video is currently sourced from the videos uploaded in Sanity (as I think you referred to)

2021-03-09 11:14 UTC, TheKnarf submitted a review, later dismissed

2021-03-10 08:01 UTC, TheKnarf approved these changes

2021-03-10 12:09 UTC, merged