update social share
Alv-no/alv-website pull request #290
Opened 2021-03-26 23:59 UTC by mikkelcodes

2021-03-27 00:01 UTC, mikkelcodes commented
This needs to be tested on dev prior to sending it off to prod. 
If you'll be unavailable, I could look to test this on my own with a Netlify build.

2021-03-27 07:47 UTC, TheKnarf commented
Automatic deployment pipeline should now be working for dev, so if we merge it in that should be deployed.

2021-03-27 07:48 UTC, TheKnarf commented on packages/cms/schemas/schema.js
> -    // featuredTeam,
Why is featured team removed?

2021-03-27 07:49 UTC, TheKnarf commented on packages/website/src/components/socialShare/index.js
> +        <FacebookShareButton url={'www.google.no'} quote={title} hashtag={tags}>
Why should the facebook share button go to google?

2021-03-27 09:46 UTC, TheKnarf requested changes
Please look at the comments above.

2021-03-27 10:20 UTC, TheKnarf commented on packages/website/src/templates/article.js
> +        : null;
Seems like these lines maybe should be moved into the hook?

2021-03-27 10:23 UTC, TheKnarf commented on packages/cms/package.json
> +    "deploy-all": "sanity graphql deploy --playground && sanity deploy",
Not sure this task is needed? You can always run `yarn graphql-deploy && yarn deploy`.

But also this is ran automatically when we merge in pull requests so I don't see you ever needing to run this manually?
Maybe `yarn graphql-deploy` needs to be ran manually from time to time so that gatsby catches the graphql schema changes.

2021-03-27 10:53 UTC, mikkelcodes commented on packages/cms/schemas/schema.js
> -    // featuredTeam,
Because this component was replaced by a more flexible solution. I just removed the file itself also

2021-03-27 11:23 UTC, TheKnarf commented on packages/cms/package.json
> +    "deploy": "sanity deploy ",
unnessesary space?

2021-03-27 11:42 UTC, TheKnarf approved these changes

2021-03-28 10:08 UTC, TheKnarf submitted a review, later dismissed

2021-03-29 14:43 UTC, TheKnarf approved these changes

2021-03-29 14:44 UTC, merged