fix bux
Alv-no/alv-website pull request #300
Opened 2021-04-07 05:22 UTC by mikkelcodes

2021-04-08 08:23 UTC, TheKnarf commented on packages/website/gatsby-config.js
> -      resolve: 'gatsby-plugin-google-tagmanager',
Why is this removed?

2021-04-08 08:25 UTC, TheKnarf commented on packages/website/src/components/checkbox/index.js
> +  if (defaultChecked === undefined) defaultChecked = false;
I don't think that we should keep changing this file back and forth. We have changed the defaultChecked value several times now.... Maybe just change how you use the component instead of changing this file? Every time you change it you also change the test / have to change the test; and the point of unit tests are to test that the code work as intended, not to keep changing it. If we have a unit test for something that is intended to mean that this component work as intended.

So change the use of the component not the component itself.

2021-04-08 08:26 UTC, TheKnarf commented on packages/website/src/components/employeeSection/index.js
> +  useEffect(() => {
This can probably be refactored into using an `useMemo`?

2021-04-08 08:27 UTC, TheKnarf commented on packages/website/src/components/imageTextFull/index.js
> +import styles from '../../templates/Service.module.css';
This component should probably have it's own css-module instead of importing a css module from somewhere else? If you need some shared style then refactor that into it's own component or use css variables.

2021-04-08 08:28 UTC, TheKnarf commented on packages/website/src/components/navigation/index.js
> +            categoryPages.slice(0, 2).map((categoryPage) => {
Why are we slicing to `2` here? Maybe take that out into a variable so that it's easier to read the code instead of using a "magic number".

2021-04-08 08:28 UTC, TheKnarf commented on packages/website/src/components/navigation/index.js
> +            categoryPages.slice(2, categoryPages.length).map((categoryPage) => {
Why are we slicing to `3` here? Maybe take that out into a variable so that it's easier to read the code instead of using a "magic number".

2021-04-08 08:29 UTC, TheKnarf commented on packages/website/src/components/navyIntroImage/index.js
> +              title.length > 15
Why are we switching on `title.length` here? That seems weird. At least take the `title.length > 15` portion out into its own variable so that someone who reads the code knows what it is.

2021-04-08 08:30 UTC, TheKnarf commented on packages/website/src/pages/vi-tilbyr.js
> +                  (card) => card.parentPage.slug.current === 'systemutvikling'
Why are we filtering on `systemutvikling` here? We probably shouldn't have that hardcoded. This feels like something that should live in Sanity.

2021-04-08 08:31 UTC, TheKnarf commented on packages/website/src/templates/Service.module.css
> +.mainImage {
Why is all of this a css-module and not just tailwindcss?

2021-04-08 08:31 UTC, TheKnarf requested changes
I'd like to either get clearance in the issues over, or have them fixed.

2021-04-08 11:44 UTC, mikkelcodes commented on packages/website/gatsby-config.js
> -      resolve: 'gatsby-plugin-google-tagmanager',
To my understanding, we're only using the Google Analytics part and a separate google analytics plugin already takes care of that embed. Furthermore, it started throwing strange errors here and there although it wasn't really doing anything. Removed it as a quick fix and we can look to reintroduce it later if necessary

2021-04-08 12:39 UTC, mikkelcodes commented on packages/website/src/components/checkbox/index.js
> +  if (defaultChecked === undefined) defaultChecked = false;
Yep, that makes sense

2021-04-08 13:35 UTC, mikkelcodes commented on packages/website/src/components/imageTextFull/index.js
> +import styles from '../../templates/Service.module.css';
I'll create an issue to define a global blockcontent (from sanity) css stylesheet.

2021-04-08 13:37 UTC, mikkelcodes commented on packages/website/src/components/navigation/index.js
> +            categoryPages.slice(0, 2).map((categoryPage) => {
Yes - good one. When I think about it, this should be improved programmatically - the number should be determined based on how many child pages each category have.

2021-04-08 13:38 UTC, mikkelcodes commented on packages/website/src/components/navigation/index.js
> +            categoryPages.slice(2, categoryPages.length).map((categoryPage) => {
Same as above

2021-04-08 13:44 UTC, mikkelcodes commented on packages/website/src/components/navyIntroImage/index.js
> +              title.length > 15
I discussed this issue yesterday with Jakob and we decided we'll do a separate field in Sanity to replace this functionality with something more flexible. It's about long words that need to scale down to fit in the view. As per mobile design spec, the font size of category/service page titles are way too large for several titles containing 20+ characters

2021-04-08 13:47 UTC, TheKnarf submitted a review, later dismissed
Approving the PR with the assumption that you have made issues out of the things we have discussed.

2021-04-08 20:19 UTC, mikkelcodes commented on packages/website/src/templates/Service.module.css
> +.mainImage {
Because we can't reach jsx-elements generated by the PortableText component directly with tailwind. PortableText is a package from sanity that converts Rich Text into jsx-elements.

2021-04-08 20:20 UTC, mikkelcodes commented on packages/website/src/templates/Service.module.css
> +.mainImage {
I will consolidate a few of the template page CSS stylesheets. Made an issue on it

2021-04-09 06:54 UTC, TheKnarf approved these changes

2021-04-09 08:00 UTC, merged