update long word formatting - service card
Alv-no/alv-website pull request #317
Opened 2021-04-14 13:35 UTC by mikkelcodes

2021-04-14 13:49 UTC, TheKnarf commented on packages/website/src/components/servicesCard/index.js
> +const SplitWord = ({ word }) => {
Is this really needed? Isn't it enough to do `text-overflow: ellipsis` or something similare?

2021-04-14 13:53 UTC, TheKnarf requested changes

2021-04-14 13:53 UTC, TheKnarf commented on packages/website/src/components/servicesCard/index.js
> +      {formattedWord &&
Just use `if` and have two return statements...

2021-04-14 13:54 UTC, mikkelcodes commented on packages/website/src/components/servicesCard/index.js
> +const SplitWord = ({ word }) => {
I think it is :/ These are titles like "systemutviklingsledelse" that are split into:
"systemutviklings-
ledelse"
and ending it with "systemutviklings..." might not be practical. But the method you proposed could be applied to blog post card descriptions to simplify things.

2021-04-14 13:59 UTC, TheKnarf commented on packages/website/src/components/servicesCard/index.js
> +const SplitWord = ({ word }) => {
Css hypens then? https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

2021-04-14 17:41 UTC, mikkelcodes commented on packages/website/src/components/servicesCard/index.js
> +const SplitWord = ({ word }) => {
<img width="297" alt="Screenshot 2021-04-14 at 19 40 17" src="https://user-images.githubusercontent.com/61052733/114754828-4c23d900-9d59-11eb-8f0b-e2aa4f94bd99.png">

Is this an acceptable look? (css hyphens)

2021-04-15 07:40 UTC, TheKnarf commented on packages/website/src/components/servicesCard/index.js
> +const SplitWord = ({ word }) => {
Seems fine for me.

2021-04-15 08:18 UTC, TheKnarf requested changes

2021-04-15 08:18 UTC, TheKnarf commented on packages/website/src/components/servicesCard/index.js
> +const SplitWord = ({ titleSplit, title }) => (
Remove unused component.

2021-04-15 12:52 UTC, mikkelcodes commented on packages/website/src/components/navyIntro/index.js
> -          <div className="bg-navy bg-opacity-75 w-full pt-10 sm:h-50vh h-screen flex flex-col justify-center items-center sm:pt-16 sm:pb-16 pb-4">
This line is from and resolves issue #301 but the same file also contains fixes for #307 (wordwrap)

2021-04-15 17:05 UTC, TheKnarf approved these changes

2021-04-15 18:01 UTC, merged