title component added
Alv-no/alv-website pull request #41
Opened 2020-11-08 21:57 UTC by mikkelcodes

Added some commonly used font-size and line-height combinations to tailwind also

2020-11-08 22:29 UTC, TheKnarf commented on packages/website/src/components/title/Title.js
> +    {title.toUpperCase()}
Maybe this could be solved with css instead using `text-transform: uppercase;`?

2020-11-08 22:30 UTC, TheKnarf commented on packages/website/src/components/title/Title.js
> +import React from 'react';
I would prefer to keep the filename of this component as `index.js` as it originally was. I also prefer to keep filenames all lowercase.

2020-11-08 22:30 UTC, TheKnarf requested changes
Three small comments, otherwise it looks good!

2020-11-08 23:17 UTC, TheKnarf commented on packages/website/src/components/title/Title.js
> +export const Title = ({ title }) => (
Instead of `({ title }) =>` it would  probably be more appropriate to use `({ children }) =>` here.

2020-11-09 01:00 UTC, mikkelcodes commented on packages/website/src/components/title/Title.js
> +    {title.toUpperCase()}
It sure can be solved that way.

2020-11-09 01:01 UTC, mikkelcodes commented on packages/website/src/components/title/Title.js
> +import React from 'react';
Okay, got it. I'll stick to that from now on and update the files.

2020-11-09 11:09 UTC, TheKnarf commented on packages/website/src/pages/index.js
> +import Layout from '../components/layout/index';
Since the file is called `index` you can instead import it as just `../components/layout`, you don't need the `index`-part ( that is kinda the point of calling the file index inside a folder ;-) )

2020-11-09 11:18 UTC, mikkelcodes commented on packages/website/src/components/title/Title.js
> +export const Title = ({ title }) => (
If you don't need the possibility of editing page titles in Sanity, it makes sense to update this. Otherwise, it would just be title={data.sanityPage.title} once cms side is configured. This is what I had in mind when I wrote this. Thoughts?

2020-11-09 11:19 UTC, TheKnarf commented on packages/website/src/components/title/Title.js
> +export const Title = ({ title }) => (
Would that not work just as well with `<Title>{data.sanityPage.title}</Title>`?

2020-11-09 11:23 UTC, mikkelcodes commented on packages/website/src/components/title/Title.js
> +export const Title = ({ title }) => (
Yes it would, its only slightly longer and I thought that <Title title={title}/> was descriptive enough. I will update it once again

2020-11-09 11:27 UTC, TheKnarf commented on packages/website/src/components/title/Title.js
> +export const Title = ({ title }) => (
`<Title>{data.sanityPage.title}</Title>` and `<Title title={data.sanityPage.title}/` is exactly the same length ;-)

2020-11-09 11:27 UTC, mikkelcodes commented on packages/website/src/pages/index.js
> +import Layout from '../components/layout/index';
Ahh, now it makes total sense with this naming style when components have their own folders. Ill update this

2020-11-09 11:53 UTC, TheKnarf commented on packages/website/src/components/title/index.stories.js
> +  console.log(children);
This console.log can be deleted

2020-11-09 12:09 UTC, TheKnarf approved these changes
Looking good!

2020-11-09 12:11 UTC, merged