add employees backend, data sourcing, filtering feature
Alv-no/alv-website pull request #55
Opened 2020-11-11 17:01 UTC by mikkelcodes

I recommend we use gatsby-image for standalone images. This gives us lazy-loading, an optional image blur-up effect (pretty cool imo) and great file-size compression. Sanity has their own gatsby graphql fragments we can use too. 

This is why I have thrown in a few dependencies related to images. I might use this with the employee photos.

Otherwise, the filtering should work fine now

2020-11-11 17:09 UTC, mikkelcodes commented
Også verdt å nevne: teksten på bildene er lite synlige i default state. Dette er på todo

2020-11-11 20:36 UTC, TheKnarf commented on packages/cms/schemas/tag.js
> +  name: 'tag',
Should this have been called `employee_tags` or something similar?

2020-11-11 20:37 UTC, TheKnarf commented on packages/website/package.json
> +    "intersection-observer": "^0.11.0",
All of these gatsby plugins should probably be moved under `devDependencies`

2020-11-11 20:38 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +      {/* EMPLOYEE CARDS */}
Can `EmployeeCard` get its own component?

2020-11-11 20:38 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +                backgroundOpacity: '0',
If background size and opacity is static, should they not be styled by className?

2020-11-11 20:39 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +                  </span>{' '}
An extra space added here `{' '}` that can be removed.

2020-11-11 20:41 UTC, TheKnarf requested changes
A couple of comments, but otherwise this looks good! Mainly I think we perhaps should refactor `tagbar` a bit as it's starting to get a bit big. At least an employee card should have its own component.

2020-11-11 21:09 UTC, mikkelcodes commented on packages/website/src/components/tagbar/index.js
> +                backgroundOpacity: '0',
> A couple of comments, but otherwise this looks good! Mainly I think we perhaps should refactor `tagbar` a bit as it's starting to get a bit big. At least an employee card should have its own component.

Thank you for the comments. I will have these things updated in a sec along with a few other changes.

2020-11-11 22:23 UTC, mikkelcodes commented on packages/cms/schemas/tag.js
> +  name: 'tag',
Makes sense

2020-11-11 23:44 UTC, TheKnarf commented on packages/cms/schemas/schema.js
> +    tag,
Should this too be renamed to employee_tags?

2020-11-11 23:46 UTC, TheKnarf commented on packages/website/src/components/employeeCard/index.js
> +  const { image, id, experience, firstname, lastname, title } = data;
It would probably be cleaner to have something like:

```
export const EmployeeCard = ({ image, id, experience, firstname, lastname, title }) => {
```

And then when using it one could use it as:

```
<EmployeeCard {...data} />
```

Or something similare.

2020-11-11 23:46 UTC, TheKnarf commented on packages/website/src/components/employeeCard/index.stories.js
> +export const Default = () => <EmployeeCard />;
Add some test data here?

2020-11-11 23:48 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
>  import { Tag } from '../icon';
To make it slightly more clear that this is in-fact an icon we could import it as following:

```
import * as Icon from '../icon';
```

and then use it as:

```
<Icon.Tag />
```

That makes it easier to understand when reading the code that it's an icon we're importing and using and not a tag in itself.

2020-11-11 23:50 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +  const sanityEmployees = data.allSanityEmployee.edges;
Could the GraphQL stuff be moved out of the component itself and instead be ran as a part of the page? That way components inside `src/components` are somewhat `"pure"`, by which I mean that they don't do any data fetching. And only pages do fetch any data.

That also would mean that it would be easy to add anything from `src/components` to Storybook since we won't have to mock out the graphql / data fetching part.

2020-11-11 23:50 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +              <button
Instead of using button here you could use the new `src/component/checkbox`-component.

2020-11-11 23:53 UTC, TheKnarf commented
I still have a few refactoring ideas that I commented on, but we're getting closer! :-)

2020-11-11 23:57 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +      <div className="grid gap-4 justify-center mx-auto sm:grid-cols-employees-sm nine:grid-cols-employees-nine 2xl:grid-cols-employees-lg">
Maybe also take this bit out as a `Employees` component?

2020-11-12 00:00 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +    return setEmployees(filteredEmployees);
The `return` doesn't do anything here?

2020-11-12 00:01 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +  const [employees, setEmployees] = useState(sanityEmployees);
Maybe rename this from `employees` and to `filtered_employees`?

2020-11-12 00:02 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +        arr.push(sanityTag.node.tag);
This bit can be rewritten as a map-function:

```
const arr = sanityTags.map(sanityTag => sanityTag.node.tag);
```

2020-11-12 00:05 UTC, TheKnarf commented on packages/website/src/components/tagbar/index.js
> +  const [loaded, setLoaded] = useState(false);
This variable doesn't seem to be used anywhere except for in that one useEffect under, and therefore we should be able to actually just remove it. It doesn't seem to actually do anything. Instead under on line 16, we could just check for `if(sanityTags !== undefined && sanityTags !== null)` or something similar.

2020-11-12 12:48 UTC, mikkelcodes commented on packages/website/src/components/tagbar/index.js
> +  const sanityEmployees = data.allSanityEmployee.edges;
This is exactly what I meant to do. The query is intended for the whole employee page, hence the name useEmployeeQuery, and later, useBlogQuery, useArticleQuery, etc. Good catch..

2020-11-12 12:48 UTC, mikkelcodes commented on packages/website/src/components/tagbar/index.js
> +      <div className="grid gap-4 justify-center mx-auto sm:grid-cols-employees-sm nine:grid-cols-employees-nine 2xl:grid-cols-employees-lg">
Done

2020-11-12 13:02 UTC, mikkelcodes commented on packages/website/src/components/tagbar/index.js
> +    return setEmployees(filteredEmployees);
Return test? I just updated it btw. It returns the boolean of whether an employee's tag matches with the currently "activated" employee tags.

2020-11-12 13:03 UTC, mikkelcodes commented on packages/website/src/components/tagbar/index.js
> +        arr.push(sanityTag.node.tag);
Totally.

2020-11-12 13:39 UTC, mikkelcodes commented on packages/website/src/components/tagbar/index.js
> +              <button
Noted. Alright if I will update this with the next PR ?

2020-11-12 15:36 UTC, TheKnarf approved these changes

2020-11-12 15:38 UTC, merged