Feature/landing page
Alv-no/alv-website pull request #765
Opened 2022-09-30 07:01 UTC by klyngen

closes #661 
closes #663

2022-11-11 11:00 UTC, TheKnarf commented on .vscode
> +{
Probably don't add hard coded paths in a `.vscode` file that has your username in it.

2022-11-11 11:01 UTC, TheKnarf commented on Makefile
> +	cd packages/cms; npx sanity dataset export production backup.tar.gz --raw --no-asset --overwrite;
Instead of using `npx sanity` use instead `yarn workspace cmd sanity dataset export`. `npx` doesn't use the yarn lockfile to determine version and can as such be version mismatches, as well as extra time usage as it has to download sanity twice. Better perhaps to ensure that we update the sanity package.

2022-11-11 11:03 UTC, TheKnarf commented on Readme.md
> +| Package                                           | Description                                                          |
Maybe don't change this? This will require you to update all of the lines everytime you add an item with a longer description.

2022-11-11 11:03 UTC, TheKnarf commented on packages/cms/production-export-2022-09-01t19-39-23-675z/assets.json
> +{}
What is this, do we need to commit it?

2022-11-11 11:04 UTC, TheKnarf commented on packages/website/postcss.config.js
>  // Fix based on: https://github.com/storybookjs/storybook/issues/6319#issuecomment-661256439
Maybe remove the comment as well if the fix that this was reffering to is no longer needed.

2022-11-11 11:05 UTC, TheKnarf commented
<img width="543" alt="Screenshot 2022-11-11 at 12 05 23" src="https://user-images.githubusercontent.com/213777/201327678-cd2914a0-f0b9-43f1-b4b4-673648f77471.png">
This link on the homepage just goes to google.com...

2022-11-11 11:06 UTC, TheKnarf commented
<img width="1164" alt="Screenshot 2022-11-11 at 12 05 53" src="https://user-images.githubusercontent.com/213777/201327758-7c57e9a3-d66e-48b0-8b35-cadb04e19190.png">
Was there supposed to be a picture here and not just a blank square?

2022-11-11 11:07 UTC, TheKnarf commented
<img width="1904" alt="Screenshot 2022-11-11 at 12 06 41" src="https://user-images.githubusercontent.com/213777/201327853-b544e473-6cf6-4c8a-90bb-755260870035.png">

Something happened with the layout here.

2022-11-11 11:07 UTC, klyngen commented on Readme.md
> +| Package                                           | Description                                                          |
I think this is auto-formatting from my editor. Will fix

2022-11-11 11:07 UTC, klyngen commented on .vscode
> +{
Will kill it. This is my local editor config for emacs

2022-11-11 11:07 UTC, klyngen commented on packages/cms/production-export-2022-09-01t19-39-23-675z/assets.json
> +{}
Will remove it

2022-11-11 11:08 UTC, TheKnarf commented
<img width="1904" alt="Screenshot 2022-11-11 at 12 07 28" src="https://user-images.githubusercontent.com/213777/201327952-7ad542ac-c4f2-4c1f-94f5-27641730721c.png">
The `X` seems to be align weird here.

Also there is a scrolling bug when the menu is open.

2022-11-11 11:08 UTC, TheKnarf requested changes
Several mayor problems blocking this PR.

2022-11-11 11:12 UTC, TheKnarf commented
<img width="371" alt="Screenshot 2022-11-11 at 12 12 35" src="https://user-images.githubusercontent.com/213777/201328793-b7b20b37-17cd-4107-a513-c95912143226.png">
An extra space here.

2022-11-12 11:41 UTC, TheKnarf commented
Whats up with the `backup.ndjson` file?

2022-11-12 11:43 UTC, TheKnarf commented on packages/website/package.json
> +    "postcss": "latest",
Can we write the actual version number here instead of just latest?

2022-11-12 11:46 UTC, TheKnarf commented
<img width="1937" alt="Screenshot 2022-11-12 at 12 46 25" src="https://user-images.githubusercontent.com/213777/201472506-a65089eb-8b36-46ad-88d5-f11d4c38b2b8.png">
Clicking on an employee breaks the layout.

2022-11-12 12:42 UTC, TheKnarf approved these changes

2022-11-12 13:07 UTC, merged