Hire text
Alv-no/alv-website pull request #793
Opened 2022-11-21 12:14 UTC by mikkelklokkerud

2022-11-21 12:41 UTC, klyngen requested changes

2022-11-21 12:41 UTC, klyngen commented on packages/shared-components/src/components/container/index.js
> +      <div className={`max-w-${maxWidth || '1200'} mx-auto`}>{children}</div>
Here we have conditionals that decide the tailwind-css-classes. This might not look correct after the tailwind-pruning. I suggest using the styles-property to override `max-w-1200`

2022-11-21 12:41 UTC, klyngen commented on packages/shared-components/src/components/hire/index.js
> +          buttonText && 'mb-16'
Conditionals and tailwind-css-pruning is a combo that works perfectly during development and can supprise you in prod.

2022-11-21 13:52 UTC, klyngen commented
On a more general note. The `Hire`-component is used by both Alv's. Personally I like how the Hire-component looks now, I guess that change is good as long as it's fine with Jakob.

2022-11-22 10:37 UTC, mikkelklokkerud commented on packages/shared-components/src/components/hire/index.js
> +          buttonText && 'mb-16'
According to the same [tailwindcss docs](https://tailwindcss.com/docs/content-configuration#dynamic-class-names) as well as our currently deployed websites this works just fine. However, I'm changing from && operator to ternary to avoid `false` as a classname if `buttonText` is fasly. 

Sounds ok?

2022-11-22 10:39 UTC, mikkelklokkerud commented
> On a more general note. The `Hire`-component is used by both Alv's. Personally I like how the Hire-component looks now, I guess that change is good as long as it's fine with Jakob.

Great. And this UI change has been approved by the marketing department

2022-11-22 14:10 UTC, klyngen commented on packages/shared-components/src/components/container/index.js
> +      <div className={`max-w-${maxWidth || '1200'} mx-auto`}>{children}</div>
Sounds great :+1:

2022-11-22 14:11 UTC, klyngen commented on packages/shared-components/src/components/hire/index.js
> +          buttonText && 'mb-16'
Sound good! Simplifies bughunting in the future :+1:

2022-11-22 14:12 UTC, klyngen approved these changes

2022-11-22 14:30 UTC, merged