954: add chatlio live chat widget
Alv-no/alv-website pull request #955
Opened 2023-08-22 10:20 UTC by Fordiboii

Closes #954.

2023-08-22 11:09 UTC, klyngen requested changes
Remove mail-api changes

2023-08-22 11:09 UTC, klyngen commented on packages/mail-api/src/index.js
>  app.listen(port, () => {
This is not relevant for this PR

2023-08-22 11:10 UTC, klyngen commented
![image](https://github.com/Alv-no/alv-website/assets/14232560/b907ae34-0e9b-4f06-a6a1-3ba0b8660ad1)
Build is failing. Run a local build to see if you get the same issues. The failing build is preventing you from getting a review-environment.

2023-08-22 12:28 UTC, Fordiboii commented on packages/mail-api/src/index.js
>  app.listen(port, () => {
Had to fix it to allow committing

2023-08-22 14:32 UTC, klyngen commented
💻 https://954-live-c-955.review.test-alv.no

2023-08-23 07:20 UTC, klyngen approved these changes

2023-08-23 07:20 UTC, merged